### ISSUE TITLE
Messages from different contacts appears in the same chat window

### ISSUE THREAD

**Issue by erijo** [licq-im/licq#13]
Steps to reproduce:
1. Have two or more messages pending from the different contacts.
2. Open them by clicking with the middle mouse button on the blinking lamp.

Result:
They all open in the same chat window.

Then when replying it is uncertain to whom the message is sent.

Probably introduced in f8990b3e.

**Comment by flynd** [comment]
Could you please check if commit 16fc9d4 solved it?

**Comment by erijo** [comment]
16fc9d4 did the trick, thanks!
