### ISSUE TITLE
Assertion failed: (false), function pluginThreadEntry

### ISSUE THREAD

**Issue by yermulnik** [licq-im/licq#18]
Yesterday I rebuilt my Licq 1.5.1 and it cannot start now:
Assertion failed: (false), function pluginThreadEntry, file /usr/ports/WORK/usr/ports/n
et-im/licq/work/licq-1.5.1/src/plugins/pluginthread.cpp, line 84.

Unfortunately, there's now gdb output:
Using gdb to save backtrace to /home/yz/.licq/licq.backtrace.gdb
Assertion failed: (false), function pluginThreadEntry, file /usr/ports/WORK/usr/ports/n
et-im/licq/work/licq-1.5.1/src/plugins/pluginthread.cpp, line 84.
/usr/src/gnu/usr.bin/gdb/libgdb/../../../../contrib/gdb/gdb/solib-svr4.c:1443: internal
-error: legacy_fetch_link_map_offsets called without legacy link_map support enabled.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? (y or n) n

Tracing with gdb (gdb /usr/local/bin/licq) shows:
(gdb) run
Starting program: /usr/local/bin/licq
<skipped "(no debugging symbols found)..." lines>
[New Thread 28801140 (LWP 100234/initial thread)]
[New Thread 28850140 (LWP 100293/licq)]
[New Thread 2884fec0 (LWP 100294/licq)]
<skipped "(no debugging symbols found)..." lines>
[New Thread 2884fd80 (LWP 100295/licq)]
Assertion failed: (false), function pluginThreadEntry, file /usr/ports/WORK/usr/ports/net-im/licq/work/licq-1.5.1/src/plugins/pluginthread.cpp, line 84.

Program received signal SIGABRT, Aborted.
[Switching to Thread 2884fd80 (LWP 100295/licq)]
0x286e64ab in thr_kill () from /lib/libc.so.7
(gdb) The program is running.  Exit anyway? (y or n) y

11:24:37 [yz@yz][~]> uname -srm
FreeBSD 8.2-STABLE i386

What could cause this error and what can I do to make Licq work?

Thanx in advance for help.

**Comment by erijo** [comment]
A very strange problem. Is it possible for you to test version 1.6.0?

**Comment by yermulnik** [comment]
Unfortunately, there's no version 1.6.0 in FreeBSD's ports tree =( And, probably, I won't be able to build without FreeBSD specific patches.
I've found the same problem you had participated a year ago, but there where no thread continuation:
http://www.mail-archive.com/licq-dev@googlegroups.com/msg00970.html

I suspect that the problem could be caused by some library or dependency update made recently on my sendbox. But I can't imagine which of them exactly it is.

**Comment by flynd** [comment]
Confirmed via mail that 2f25b63 solves it.
