### ISSUE TITLE
editbox in message window steals X-window selected URL

### ISSUE THREAD

**Issue by jan-spurny** [licq-im/licq#20]
When I select URL in www-browser and switch to open licq window, it automagically changes type of message to URL (which is almost never what I want, but never mind) and pastes the selected URL in. However, when I try to paste the URL into a different window (let's say some text editor), the selection is gone - licq-qt4 has erased the selection!
I'm pretty sure this is a bug - I can't imagine any reason for any application to wipe out the X-window selection buffer on "paste".

Licq-qt4 version: 1.3.9
My system is: Debian GNU/Linux 6.0.5,  kernel 3.2.0 x86_64, xorg 1.10.4

**Comment by flynd** [comment]
Hint: If you don't want Licq to check for URLs or files in the clipboard you can just tell it not to.
Settings -> Chat ->Check clipboard For URLs/files

**Comment by flynd** [comment]
I couldn't reproduce the issue, but the code did clear() on the clipboard after getting an URL or filename so I just removed that.
Fix will be included in Licq 1.6.2 or 1.7.0 (whichever is released next).
