### ISSUE TITLE
turkish translation for 1.8 licq-gui and osd plugin

### ISSUE THREAD

**Issue by gultekin-e** [licq-im/licq#33]
hi everyone , im frome http://www.pisilinux.org/ 
for plugin qt4-gui tr.ts: https://github.com/pisilinux/PisiLinux/raw/master/network/chat/licq/files/tr.ts
for plugin osd : https://github.com/pisilinux/PisiLinux/raw/master/network/chat/licq/files/tr.po
best regards
Erdinç

**Comment by flynd** [comment]
Thank you very much!!
Many of our translations are badly maintained so this is much appreciated.

In the core, there are also some translations for strings like "online", "not available", etc. Do you feel up to translating those as well? There is currently no turkish translation so you'll have to start from scratch but we can help you set it up if you need.

Can I also add you as translation maintainer? I got you name from github, but there is also place for an email address if you want to have it public. (However I can't guarantee anything about visibility to spambots.)
If you haven't already, you can subscribe to the licq-dev mailing list. There is always a a week or two notice before a new release is made which is a good time to update the translation for upcoming releases.

**Comment by gultekin-e** [comment]
I have translated almost entirely from the beginning. yes, we could make ,is packed as .pisi files for our repo , and we now use it in  system. https://github.com/pisilinux/PisiLinux/tree/master/network/chat/licq with no naughtiness :)

that is our python build method for pisi: https://github.com/pisilinux/PisiLinux/blob/master/network/chat/licq/actions.py
All plugins can be run successfully
the old translation was horrible, and  there were some German-azerbaijani-turkish words, 
I am self-developer of pisilinux , and I'll feel good if I can help you :) my mail adress erdincgultekin@pisilinux.org

**Comment by flynd** [comment]
I've pushed you translations for qt4-gui and osd to 1.8-stable and will merge it to master later.
If you make a translation for the core as well, it would be great.
