### ISSUE TITLE
Big load by protocol plugins (icq and jabber)

### ISSUE THREAD

**Issue by asy972** [licq-im/licq#38]
Hello.

I use Licq 1.8 on 3 hosts (with same UIN/JID). I detect big load on one host today (CPU with one core). This is 100% reproducible today. Both protocols work despite the load. A little later I'll check this on the other two hosts. 

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 25687 user       20   0  149M  27M  17M R 40.8  1.3  13:39.99 jabber/3
 25683 user       20   0  149M  27M  17M R 40.5  1.3  13:40.44 licq

strace output is same for both process:

 $ strace -p 25687
 Process 25687 attached
 poll([{fd=12, events=POLLIN}, {fd=21, events=POLLIN}], 2, 0) = 0 (Timeout)
 clock_gettime(CLOCK_MONOTONIC, {2255151, 932572108}) = 0
 poll([{fd=12, events=POLLIN}, {fd=21, events=POLLIN}], 2, 0) = 0 (Timeout)
 clock_gettime(CLOCK_MONOTONIC, {2255151, 933384975}) = 0

 $ strace -p 25683
 Process 25683 attached
 poll([{fd=3, events=POLLIN}, {fd=9, events=POLLIN}], 2, 0) = 0 (Timeout)
 clock_gettime(CLOCK_MONOTONIC, {2255317, 37286990}) = 0
 poll([{fd=3, events=POLLIN}, {fd=9, events=POLLIN}], 2, 0) = 0 (Timeout)
 clock_gettime(CLOCK_MONOTONIC, {2255317, 38095607}) = 0

**Comment by erijo** [comment]
Which OS?

Have you suspended the system?

**Comment by asy972** [comment]
> Which OS?

Sorry, all 3 is Linux.

> Have you suspended the system?

No. This is desktop w/o suspend. I checked Licq on other two hosts, it works without high load.

**Comment by flynd** [comment]
How easy can you reproduce it?
Does it happen immediately after startup? After going online? After sending/receiving any message?

Do you use NTP or similar service that adjusts the system clock?

**Comment by asy972** [comment]
> How easy can you reproduce it ?

It was reproduced in 100% of cases within a few minutes after going online without any messages. But this host is workstation with long uptime and uptime was about 30 days. Workstation was rebooted yestarday and bug is not reproduced since reboot.

> Do you use NTP or similar service that adjusts the system clock?

Ntpdate adjusts the clock every hour.

**Comment by flynd** [comment]
If this is related to NTP adjusting the time, commit 862fa82d14815a29771b02a7cf2da593db4f91f6 should solve it.

**Comment by asy972** [comment]
I tested it with uptime 26 days 20 hours. Bug reproduced with Licq 1.8. Licq 1.8.1 works without this bug. So, it's realy closed, thanks.
