### ISSUE TITLE
__assert_fail_base: Process /usr/bin/licq was killed by signal 6 (SIGABRT)

### ISSUE THREAD

**Issue by cicku** [licq-im/licq#39]
Please see:

https://bugzilla.redhat.com/show_bug.cgi?id=1023891

I think there might have some thing wrong with KDE.

**Comment by flynd** [comment]
The stack trace shows an event object being deleted twice from the ICQ plugin.
I can't find any information in that bug report on how the fault was triggered or if it is reproducible so it's hard to do anything with it.
I'm curious though to why this would be related to KDE?

**Comment by cicku** [comment]
Because many bugs received of assertion failure.

I will investigate later.

Hmm...

**Comment by flynd** [comment]
Closing ticket as there has been no reply from author and there is no information on how to reproduce the fault. If fault still exists, please re-open ticket and include more details on how the fault was triggered.

**Comment by flynd** [comment]
This problem was seen again by another user on the licq-devel mailing list. After receiving additional information and packet dumps I believe this ticket has been solved by the above commit.
