### ISSUE TITLE
Cannot build licq archlinux

### ISSUE THREAD

**Issue by myallod** [licq-im/licq#45]
lek@myallod:~/Downloads/src/licq$ git pull
Already up-to-date.
lek@myallod:~/Downloads/src/licq$ git log -1
commit 3378d190fb53dff69591dff3cb45111bc0d5d4ec
Author: Anders Olofsson flynd@licq.org
Date:   Mon Oct 6 21:05:24 2014 +0200

```
qt-gui: Move emoticon selection to widgets dir
```

ek@myallod:~/Downloads/src/licq/build-all$ LC_ALL=C make
[  1%] Built target licq_rms
[  2%] Built target licq_dbus
[  3%] Built target protocol_jabber
[  7%] Built target protocol_icq
[  7%] Generating be.qm
Usage:
    lrelease [options] project-file
    lrelease [options] ts-files [-qm qm-file]

lrelease is part of Qt's Linguist tool chain. It can be used as a
stand-alone tool to convert XML-based translations files in the TS
format into the 'compiled' QM format used by QTranslator objects.

Options:
    -help  Display this information and exit
    -idbased
           Use IDs instead of source strings for message keying
    -compress
           Compress the QM files
    -nounfinished
           Do not include unfinished translations
    -removeidentical
           If the translated text is the same as
           the source text, do not include the message
    -markuntranslated <prefix>
           If a message has no real translation, use the source text
           prefixed with the given string instead
    -silent
           Do not explain what is being done
    -version
           Display the version of lrelease and exit
qt-gui/po/CMakeFiles/qt-gui_translations.dir/build.make:68: recipe for target 'qt-gui/po/be.qm' failed
make[2]: **\* [qt-gui/po/be.qm] Error 1
CMakeFiles/Makefile2:501: recipe for target 'qt-gui/po/CMakeFiles/qt-gui_translations.dir/all' failed
make[1]: **\* [qt-gui/po/CMakeFiles/qt-gui_translations.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: **\* [all] Error 2

lek@myallod:~/Downloads/src/licq/build-all$ lrelease-qt4 -version
lrelease version 4.8.6

**Comment by erijo** [comment]
Please retest to see that it works for you.

**Comment by myallod** [comment]
All ok, thank you, i build and run Licq 1.9.0-f271d55/SSL

Interestingly, after install i have error:
02:09:29.928 [ERR] licq: Unable to load plugin (/usr/local/lib/licq/licq_qt4-gui.so): /usr/local/lib/licq/licq_qt4-gui.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога

I changed ~/.licq/licq.conf:
-Plugin1=/usr/local/lib/licq/licq_qt4-gui.so
+Plugin1=/usr/local/lib/licq/licq_qt-gui.so

Also, i removed ~/.licq/qt-gui/config.ini because i saw in console:
QWidget::setMinimumSize: (MainWindow/LicqQtGui::MainWindow) Negative sizes (0,-9) are not possible
